### ISSUE TITLE
HA 2023.6.0 - Unexpected exception importing component custom_components.setter

### ISSUE THREAD

**Issue by simonepittis** [dlashua/hass-setter#5]
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/setter/__init__.py:81
Integration: setter (documentation, issues)
First occurred: 08:31:47 (1 occurrences)
Last logged: 08:31:47

Unexpected exception importing component custom_components.setter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/setter/__init__.py", line 54, in <module>
    class SaverEntity(RestoreEntity):
  File "/config/custom_components/setter/__init__.py", line 81, in SaverEntity
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

 Setup failed for custom integration setter: Unable to import component: Exception importing custom_components.setter

**Comment by simonepittis** [comment]
https://github.com/dlashua/hass-setter/pull/6

this works
